apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: database  
  ports:
    - port: 3306                
      targetPort: 3306          
  type: ClusterIP              